set_property SRC_FILE_INFO {cfile:c:/Users/ianrun75/Downloads/MP1new/MP1/MP1.srcs/sources_1/bd/mp1block/ip/mp1block_processing_system7_0_0/mp1block_processing_system7_0_0/mp1block_processing_system7_0_0_in_context.xdc rfile:../../../MP1.srcs/sources_1/bd/mp1block/ip/mp1block_processing_system7_0_0/mp1block_processing_system7_0_0/mp1block_processing_system7_0_0_in_context.xdc id:1 order:EARLY scoped_inst:mp1block_i/processing_system7_0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/ianrun75/Downloads/MP1new/constraints/zedboard_master.xdc rfile:../../../../constraints/zedboard_master.xdc id:2} [current_design]
current_instance mp1block_i/processing_system7_0
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y11 [get_ports {ppmin[0]}]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11 [get_ports {ppmout[0]}]
set_property src_info {type:XDC file:2 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports -of_objects [get_iobanks 33]];
set_property src_info {type:XDC file:2 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 34]]
set_property src_info {type:XDC file:2 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports -of_objects [get_iobanks 35]]
set_property src_info {type:XDC file:2 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports -of_objects [get_iobanks 13]]
set_property src_info {type:XDC file:2 line:377 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:387 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list mp1block_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:2 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:390 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/current_state[0]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/current_state[1]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/current_state[2]}]]
set_property src_info {type:XDC file:2 line:391 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 20 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:394 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[0]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[1]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[2]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[3]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[4]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[5]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[6]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[7]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[8]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[9]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[10]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[11]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[12]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[13]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[14]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[15]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[16]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[17]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[18]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[19]}]]
set_property src_info {type:XDC file:2 line:395 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:398 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/state_equiv[0]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/state_equiv[1]} {mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/state_equiv[2]}]]
set_property src_info {type:XDC file:2 line:399 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:402 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/flop1]]
set_property src_info {type:XDC file:2 line:403 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:406 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/flop2]]
set_property src_info {type:XDC file:2 line:407 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:410 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list mp1block_i/axi_ppm_0/U0/axi_ppm_v1_0_S00_AXI_inst/ppm_cap/ready]]
set_property src_info {type:XDC file:2 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:414 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
