create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list s00_axi_aclk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/current_state[0]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/current_state[1]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/current_state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 20 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[0]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[1]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[2]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[3]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[4]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[5]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[6]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[7]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[8]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[9]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[10]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[11]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[12]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[13]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[14]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[15]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[16]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[17]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[18]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/timerwire[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/state_equiv[0]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/state_equiv[1]} {axi_ppm_v1_0_S00_AXI_inst/ppm_cap/state_equiv[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list axi_ppm_v1_0_S00_AXI_inst/ppm_cap/ready]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets s00_axi_aclk_IBUF_BUFG]
