# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ianrun75/Downloads/MP1new/MP1/MP1.srcs/sources_1/bd/mp1block/ip/mp1block_axi_ppm_0_0/mp1block_axi_ppm_0_0.xci
# IP: The module: 'mp1block_axi_ppm_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ianrun75/Downloads/MP1new/MP1/MP1.srcs/sources_1/bd/mp1block/ip/mp1block_axi_ppm_0_0/axi_ppm_v1_0_project/axi_ppm_v1_0_project.srcs/constrs_1/new/sdfsf.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp1block_axi_ppm_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/ianrun75/Downloads/MP1new/MP1/MP1.srcs/sources_1/bd/mp1block/ip/mp1block_axi_ppm_0_0/mp1block_axi_ppm_0_0.xci
# IP: The module: 'mp1block_axi_ppm_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ianrun75/Downloads/MP1new/MP1/MP1.srcs/sources_1/bd/mp1block/ip/mp1block_axi_ppm_0_0/axi_ppm_v1_0_project/axi_ppm_v1_0_project.srcs/constrs_1/new/sdfsf.xdc
# XDC: The top module name and the constraint reference have the same name: 'mp1block_axi_ppm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
