# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/ianrun75/Downloads/MP1new/constraints/zedboard_master.xdc

# Block Designs: bd/mp1block/mp1block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mp1block || ORIG_REF_NAME==mp1block} -quiet] -quiet

# IP: bd/mp1block/ip/mp1block_axi_ppm_0_0/mp1block_axi_ppm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mp1block_axi_ppm_0_0 || ORIG_REF_NAME==mp1block_axi_ppm_0_0} -quiet] -quiet

# IP: bd/mp1block/ip/mp1block_processing_system7_0_0/mp1block_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mp1block_processing_system7_0_0 || ORIG_REF_NAME==mp1block_processing_system7_0_0} -quiet] -quiet

# IP: bd/mp1block/ip/mp1block_proc_sys_reset_0_0/mp1block_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mp1block_proc_sys_reset_0_0 || ORIG_REF_NAME==mp1block_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/mp1block/ip/mp1block_xbar_0/mp1block_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mp1block_xbar_0 || ORIG_REF_NAME==mp1block_xbar_0} -quiet] -quiet

# IP: bd/mp1block/ip/mp1block_axi_interconnect_0_0/mp1block_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mp1block_axi_interconnect_0_0 || ORIG_REF_NAME==mp1block_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/mp1block/ip/mp1block_axi_gpio_0_0/mp1block_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mp1block_axi_gpio_0_0 || ORIG_REF_NAME==mp1block_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mp1block/ip/mp1block_axi_gpio_1_0/mp1block_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mp1block_axi_gpio_1_0 || ORIG_REF_NAME==mp1block_axi_gpio_1_0} -quiet] -quiet

# IP: bd/mp1block/ip/mp1block_auto_pc_0/mp1block_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mp1block_auto_pc_0 || ORIG_REF_NAME==mp1block_auto_pc_0} -quiet] -quiet

# XDC: bd/mp1block/mp1block_ooc.xdc
