# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MP0/MP0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0 || ORIG_REF_NAME==MP0} -quiet] -quiet

# IP: bd/MP0/ip/MP0_processing_system7_0_1/MP0_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_processing_system7_0_1 || ORIG_REF_NAME==MP0_processing_system7_0_1} -quiet] -quiet

# IP: bd/MP0/ip/MP0_axi_gpio_0_0/MP0_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_axi_gpio_0_0 || ORIG_REF_NAME==MP0_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MP0/ip/MP0_axi_gpio_0_1/MP0_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_axi_gpio_0_1 || ORIG_REF_NAME==MP0_axi_gpio_0_1} -quiet] -quiet

# IP: bd/MP0/ip/MP0_axi_gpio_0_2/MP0_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_axi_gpio_0_2 || ORIG_REF_NAME==MP0_axi_gpio_0_2} -quiet] -quiet

# IP: bd/MP0/ip/MP0_xbar_0/MP0_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_xbar_0 || ORIG_REF_NAME==MP0_xbar_0} -quiet] -quiet

# IP: bd/MP0/ip/MP0_ps7_0_axi_periph_0/MP0_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_ps7_0_axi_periph_0 || ORIG_REF_NAME==MP0_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/MP0/ip/MP0_rst_ps7_0_100M_0/MP0_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_rst_ps7_0_100M_0 || ORIG_REF_NAME==MP0_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/MP0/ip/MP0_system_ila_0_0/MP0_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_system_ila_0_0 || ORIG_REF_NAME==MP0_system_ila_0_0} -quiet] -quiet

# IP: bd/MP0/ip/MP0_auto_pc_0/MP0_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_auto_pc_0 || ORIG_REF_NAME==MP0_auto_pc_0} -quiet] -quiet

# XDC: bd/MP0/MP0_ooc.xdc
