# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_rst_ps7_0_100M_0/MP0_rst_ps7_0_100M_0.xci
# IP: The module: 'MP0_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_rst_ps7_0_100M_0/MP0_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_rst_ps7_0_100M_0/MP0_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_rst_ps7_0_100M_0/MP0_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_rst_ps7_0_100M_0/MP0_rst_ps7_0_100M_0.xci
# IP: The module: 'MP0_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_rst_ps7_0_100M_0/MP0_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_rst_ps7_0_100M_0/MP0_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_rst_ps7_0_100M_0/MP0_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
