# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/MP0_system_ila_1_0.xci
# IP: The module: 'MP0_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/bd_0/bd_5b0b.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5b0b || ORIG_REF_NAME==bd_5b0b} -quiet] -quiet

# IP: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/bd_0/ip/ip_0/bd_5b0b_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5b0b_ila_lib_0 || ORIG_REF_NAME==bd_5b0b_ila_lib_0} -quiet] -quiet

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5b0b_ila_lib_0 || ORIG_REF_NAME==bd_5b0b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5b0b_ila_lib_0 || ORIG_REF_NAME==bd_5b0b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/bd_0/ip/ip_0/bd_5b0b_ila_lib_0_ooc.xdc

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/bd_0/bd_5b0b_ooc.xdc

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/MP0_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/MP0_system_ila_1_0.xci
# IP: The module: 'MP0_system_ila_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/bd_0/bd_5b0b.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5b0b || ORIG_REF_NAME==bd_5b0b} -quiet] -quiet

# IP: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/bd_0/ip/ip_0/bd_5b0b_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5b0b_ila_lib_0 || ORIG_REF_NAME==bd_5b0b_ila_lib_0} -quiet] -quiet

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5b0b_ila_lib_0 || ORIG_REF_NAME==bd_5b0b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5b0b_ila_lib_0 || ORIG_REF_NAME==bd_5b0b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/bd_0/ip/ip_0/bd_5b0b_ila_lib_0_ooc.xdc

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/bd_0/bd_5b0b_ooc.xdc

# XDC: x:/cpre488/Labs/MP-0/MP-0/MP-0.srcs/sources_1/bd/MP0/ip/MP0_system_ila_1_0/MP0_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_system_ila_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
